version: 2
jobs:
  build:
    branches:
      only:
        - VARI-merge
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Build Script
          command: sh build.sh